apiVersion: apps/v1
kind: Deployment
metadata:
  name: directory-app
  namespace: demo
  labels:
    app.kubernetes.io/name: directory-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: directory-app
  template:
    metadata:
      labels:
        app: directory-app
    spec:
      containers:
        - name: directory-app
          image: nginx:stable-alpine # sample "hello world"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi